apiVersion: v1
kind: Pod
metadata:
 name: health3
 labels:
  app: v1
spec:
 containers:
  - name: health3
    image: registry.k8s.io/goproxy:0.1
    imagePullPolicy: IfNotPresent
    ports:
     - containerPort: 8080
    readinessProbe:
     tcpSocket:
      port: 8080
     initialDelaySeconds: 5
     periodSeconds: 5
    livenessProbe:
     tcpSocket:
      port: 8080
     initialDelaySeconds: 5
     periodSeconds: 5
